# Generated by Copilot
from flask import current_app, render_template_string
from flask_mail import Message
from app import mail
import threading

def send_async_email(app, msg):
    """Send email asynchronously"""
    with app.app_context():
        try:
            mail.send(msg)
        except Exception as e:
            current_app.logger.error(f'Failed to send email: {str(e)}')

def send_email(subject, recipients, text_body, html_body=None, sender=None):
    """Send email notification"""
    if not current_app.config['SEND_EMAIL_NOTIFICATIONS']:
        return
    
    msg = Message(
        subject=subject,
        recipients=recipients if isinstance(recipients, list) else [recipients],
        body=text_body,
        html=html_body,
        sender=sender or current_app.config['MAIL_DEFAULT_SENDER']
    )
    
    # Send asynchronously to avoid blocking
    thread = threading.Thread(
        target=send_async_email,
        args=(current_app._get_current_object(), msg)
    )
    thread.start()

def send_questionnaire_completed_notification(questionnaire, response):
    """Send notification when questionnaire is completed"""
    if not questionnaire.creator.email:
        return
    
    subject = f'New Response to "{questionnaire.title}"'
    
    text_body = f"""
A new response has been submitted to your questionnaire "{questionnaire.title}".

Respondent: {response.get_respondent_name()}
Submitted at: {response.submitted_at.strftime('%Y-%m-%d %H:%M:%S')}
Total responses: {questionnaire.get_total_responses()}

View the response and analytics at: {current_app.config.get('SERVER_NAME', 'your-app.com')}/questionnaire/{questionnaire.id}/analytics

Best regards,
Questionnaire Management System
    """
    
    html_body = f"""
<html>
<body>
    <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
        <h2 style="color: #0d6efd;">New Questionnaire Response</h2>
        
        <p>A new response has been submitted to your questionnaire <strong>"{questionnaire.title}"</strong>.</p>
        
        <div style="background: #f8f9fa; padding: 15px; border-radius: 5px; margin: 20px 0;">
            <p><strong>Respondent:</strong> {response.get_respondent_name()}</p>
            <p><strong>Submitted at:</strong> {response.submitted_at.strftime('%Y-%m-%d %H:%M:%S')}</p>
            <p><strong>Total responses:</strong> {questionnaire.get_total_responses()}</p>
        </div>
        
        <p>
            <a href="{current_app.config.get('SERVER_NAME', 'your-app.com')}/questionnaire/{questionnaire.id}/analytics" 
               style="background: #0d6efd; color: white; padding: 10px 20px; text-decoration: none; border-radius: 5px;">
                View Response & Analytics
            </a>
        </p>
        
        <p style="color: #6c757d; font-size: 14px; margin-top: 30px;">
            Best regards,<br>
            Questionnaire Management System
        </p>
    </div>
</body>
</html>
    """
    
    send_email(
        subject=subject,
        recipients=questionnaire.creator.email,
        text_body=text_body,
        html_body=html_body
    )

def send_welcome_email(user):
    """Send welcome email to new users"""
    subject = 'Welcome to Questionnaire Manager'
    
    text_body = f"""
Welcome to Questionnaire Manager, {user.get_full_name()}!

Your account has been successfully created. You can now:
- Create and manage questionnaires
- View detailed analytics and charts
- Track responses and completion rates
- Export data for further analysis

Get started by logging in and creating your first questionnaire.

Best regards,
The Questionnaire Manager Team
    """
    
    html_body = f"""
<html>
<body>
    <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
        <h2 style="color: #0d6efd;">Welcome to Questionnaire Manager!</h2>
        
        <p>Hello {user.get_full_name()},</p>
        
        <p>Your account has been successfully created. You can now:</p>
        
        <ul style="line-height: 1.6;">
            <li>Create and manage questionnaires</li>
            <li>View detailed analytics and charts</li>
            <li>Track responses and completion rates</li>
            <li>Export data for further analysis</li>
        </ul>
        
        <p>
            <a href="{current_app.config.get('SERVER_NAME', 'your-app.com')}/auth/login" 
               style="background: #0d6efd; color: white; padding: 10px 20px; text-decoration: none; border-radius: 5px;">
                Get Started
            </a>
        </p>
        
        <p style="color: #6c757d; font-size: 14px; margin-top: 30px;">
            Best regards,<br>
            The Questionnaire Manager Team
        </p>
    </div>
</body>
</html>
    """
    
    send_email(
        subject=subject,
        recipients=user.email,
        text_body=text_body,
        html_body=html_body
    )

def send_questionnaire_shared_notification(questionnaire, shared_with_email, shared_by_user):
    """Send notification when questionnaire is shared"""
    subject = f'Questionnaire Shared: "{questionnaire.title}"'
    
    text_body = f"""
{shared_by_user.get_full_name()} has shared a questionnaire with you.

Questionnaire: "{questionnaire.title}"
Description: {questionnaire.description or 'No description provided'}

You can view and respond to this questionnaire at: {current_app.config.get('SERVER_NAME', 'your-app.com')}/questionnaire/{questionnaire.id}

Best regards,
Questionnaire Management System
    """
    
    html_body = f"""
<html>
<body>
    <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
        <h2 style="color: #0d6efd;">Questionnaire Shared With You</h2>
        
        <p><strong>{shared_by_user.get_full_name()}</strong> has shared a questionnaire with you.</p>
        
        <div style="background: #f8f9fa; padding: 15px; border-radius: 5px; margin: 20px 0;">
            <h3 style="margin: 0 0 10px 0; color: #0d6efd;">"{questionnaire.title}"</h3>
            <p style="margin: 0;">{questionnaire.description or 'No description provided'}</p>
        </div>
        
        <p>
            <a href="{current_app.config.get('SERVER_NAME', 'your-app.com')}/questionnaire/{questionnaire.id}" 
               style="background: #0d6efd; color: white; padding: 10px 20px; text-decoration: none; border-radius: 5px;">
                View Questionnaire
            </a>
        </p>
        
        <p style="color: #6c757d; font-size: 14px; margin-top: 30px;">
            Best regards,<br>
            Questionnaire Management System
        </p>
    </div>
</body>
</html>
    """
    
    send_email(
        subject=subject,
        recipients=shared_with_email,
        text_body=text_body,
        html_body=html_body
    )